# Generated by Django 2.1.5 on 2019-01-14 04:13

import apps.profiles.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.profiles.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='identificacion'),
        ),
    ]
