version: '3'

services:
  db:
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: tesis_ps01
    environment:
      - POSTGRES_PASSWORD=1029jdsdlaksmdpowj1309u12plmsd
      - POSTGRES_USER=django
      - POSTGRES_DB=django
    expose:
      - 5432
    hostname: tesis_ps01
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: tesis_dj01
    command: bash -c "/code/utils/wait-for-it.sh postgres:5432 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=1029jdsdlaksmdpowj1309u12plmsd
      - DB_USER=django
      - DB_NAME=django
      - DB_HOST=db
      - DB_PORT=5432
      - IN_DOCKER=1
    hostname: tesis_dj01
    ports:
      - "8000:8000"
    volumes:
      - ./solidity:/code/solidity
      - ./src:/code
      - ./src/media:/code/media
      - ./utils:/code/utils
    restart: always
  ganache:
    build:
      context: .
      dockerfile: ./docker/ganache-cli/Dockerfile
    container_name: tesis_ganache_cli
    hostname: tesis_ganache_cli
    expose:
      - 8545
    restart: always