version: '3.1'

services:
  db:
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: tesis_ps01
    env_file:
      - ./.env
    expose:
      - 5432
    hostname: tesis_ps01
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: tesis_dj01
    command: bash -c "/code/utils/wait-for-it.sh postgres:5432 && python manage.py migrate && python manage.py loaddata initial && python manage.py runserver 0.0.0.0:8000"
    links:
      - ganache
    depends_on:
      - db
      - ganache
    env_file:
      - ./.env
    hostname: tesis_dj01
    ports:
      - "8000:8000"
    user: root
    volumes:
      - ./src:/code
      - ./utils:/code/utils
      - contracts:/code/static/json
    restart: always
  ganache:
    build:
      context: .
      dockerfile: ./docker/ganache/Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./src/apps/tokens/solidity:/code
      - contracts:/code/build/contracts
    container_name: tesis_ganache
    hostname: tesis_ganache
    command: sh -c "concurrently 'npm run start-ganache' 'npm run compile' "
    restart: always

volumes:
  contracts: 