# Generated by Django 2.2.2 on 2019-06-13 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('url', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Url')),
                ('port', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Puerto')),
                ('connected', models.BooleanField(default=False, verbose_name='Conectado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nombre')),
                ('token_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nombre del Token')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizacion')),
                ('token_value', models.IntegerField(default=1, verbose_name='Valor del Token')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
