# Generated by Django 2.2.2 on 2019-07-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='closed',
            field=models.BooleanField(default=True, verbose_name='Cerrada'),
        ),
    ]
