# Generated by Django 2.1.5 on 2019-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('url', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Url')),
                ('port', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Puerto')),
                ('Activo', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
