# Generated by Django 2.2.2 on 2019-07-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_pool_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Cerrada'),
        ),
    ]
