# Generated by Django 2.1.5 on 2019-02-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='Activo',
        ),
        migrations.AddField(
            model_name='network',
            name='connected',
            field=models.BooleanField(default=False, verbose_name='Conectado'),
        ),
    ]
