# Generated by Django 2.1.5 on 2019-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_auto_20190221_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='token_value',
            field=models.IntegerField(default=1, verbose_name='Valor del Token'),
        ),
    ]
