# Generated by Django 2.2.2 on 2019-07-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_auto_20190725_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pool',
            name='token_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.TokenType'),
        ),
        migrations.DeleteModel(
            name='TokenTypes',
        ),
    ]
