# Generated by Django 2.2.2 on 2019-09-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentype',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
